spring:
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtSecurity
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date: dd/MM/yyyy
application:
  security:
    jwt:
      secret-key: D51A70F140DFD01686FE543E1AC725DFC1733743947508F2E358F8FE7C5EC8F2 #404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

#  liquibase:
#    change-log:
#      classpath:/db/changelog/2024/01/02-01-changelog.xml


#logging.level.org.springframework=ERROR
#logging.level.org.springframework.security=DEBUG
#spring.jpa.hibernate.ddl-auto=none

#spring.sql.init.mode=always
#spring.sql.init.platform=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/
#spring.datasource.username=postgres
#spring.datasource.password=s$cret



#spring.datasource.url=jdbc:mysql://localhost:3306/taskTrack?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true

#
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=6feab3b006bf20
#spring.mail.password=2210ac54963489
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# importing changes loge here




#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB


#aws.bucket.name=rentalhive
#amazon.aws.accesskey=AKIA6OLOSENVLTQKCAUA
#amazon.aws.secretkey=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
#amazon.aws.region=us-east-1
